disabled_rules:
- trailing_whitespace
- function_body_length
- line_length
- force_cast
- type_name
- variable_name
- weak_delegate
- large_tuple
- function_parameter_count
- redundant_optional_initialization

excluded:
- Carthage
- Pods
- mstdn/Resources
